apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: wordpress
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:dsrUJMFTkF1zT0E=,iv:Vx9YSfQlSnhJqYl3pgTJ6+ZT8S0RwhDEUtmAnnNqATY=,tag:VV9svP+a/sdNl2Dyb1HtxQ==,type:str]
    mysql-password: ENC[AES256_GCM,data:1F18vS8qX/PlNsxvvQ==,iv:IYey9u/uK6WWtqTQn9hdVhGhdzArXQBiwtuUCxO6S8g=,tag:NC8kp4myuhEcRcgsOKoGEg==,type:str]
    mysql-username: ENC[AES256_GCM,data:ZC+GXM5Q,iv:emYnANKBbMTVnON7avEz96z9cb0rQB48WwEBo6nBbT4=,tag:jWR0oZ/+78DZadv00eQiAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ylywy24rh38xyad5syckac4kx6h6znmxer3a9yuzly5pgxpg7ddq7y6nv6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbTlScVBKUzBRY0wrcUdv
            aWlzSkl0eUpmOUxvTGtVOEFmNkVKWjZwcFVvCkJScm95eXJOSWR4TjlPV0Z6TDBI
            aGI4S3g2ZjZ4MnFhSGEvNEZ0dmdhS0kKLS0tIGhuRVBmMExkWEt3VlBmbEF3ZThG
            czZiR1N5dlNCSHFZRVBpR3JXUVVqNlEK0ZtS3IYIIM2wQvxTPLkNLOBBWB/vrtFh
            5635VtS6jha2JEXtYT5xkudmOyW5PGvbVgbnId5PuNgb4sDqB0VvtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T05:04:24Z"
    mac: ENC[AES256_GCM,data:s07wgdEFY/LaodVHsJ11kman1Wemx9Jo4594LeLO6N9gAnH2xaJNCOJnPh7a9OTebm9RWo6SvnQYVKAu5DqdVGzzm+obKwTRGa1+qektZjZyu4S8KXytds5IXdl79nSacopXSFv9Hbl91CK60V6E98OmZI7yfNpepqm1BRuNknY=,iv:DTnQFnFhzR48fHDW4KVzHKniF0Qv77gie8Us3PVI5iM=,tag:mbMsRY01LL5DlX4n2tJ00w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
