apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: flux-system
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:kVcIpyDB2g==,iv:KjRvUlA1rYiEzqPLruiOP6GyZ+DAZzCs6xd/KTeaHFQ=,tag:U/pGyJD1qrysE37xbqf2HQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:P1lyXqI=,iv:Mle8RxOoh6KsoFzv9xSxp0erC/nSK3DqY35p8e87t5g=,tag:9qZziRIy1YWqKgGOLprADg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gqldluxdc6jergx7updnw3as6yxjy5xew2wkqv4aavvep46da9yszejy32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBramZ2RmkzNTJDYVVBQm9T
            YWpZTUtQalkvbEQwME15dzZWWkJHK3EzT25NCkdGZVZiZXVtbTF2ck5hRXpROWVN
            RURFOHVlRUx3VDd5eFFNU2ZhZ1hWTUEKLS0tIDhJbkpZdWNIN25LZlVrem1uSy9F
            azQ4azI0ek5UY1VmenJ3QTczUVhGMFkKk3AF/6n3ApCHsyMm35zWVR/MCVWt0VY3
            EnY4y8CwRHmMaNKZ3APgCZNL5yEL547nX7wZ9pQsGKk4wKwX0d3zKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T12:13:23Z"
    mac: ENC[AES256_GCM,data:OUs2gd7kxDgqZdoSqFILig+yadVa/hVwBWCZeIkF50iv31jjQD6ClcgMnT/Xiqk2VDueeOWPiZuHqtscGnyNDQNlNRKTMqI1SUhNE4/GjMJ4rw+8uNMGeyElbDhJFx6E5rzavjrN8iewB6GAh7rgUYlEmkH/iaYiDkuzxkf6sMk=,iv:B0rXPCyX3wjrQOZewQ2cN0UlM/Fsd94ywia4vYlOBWk=,tag:VavfkWW4yZoQ2Wgf0gXgaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
