apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: wordpress
      version: 15.2.22
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  targetNamespace: default
  values:
    wordpressUsername: admin
    wordpressPassword: admin123
    wordpressEmail: admin@example.com
    mariadb:
      enabled: false
    externalDatabase:
      host: mysql.default.svc.cluster.local
      user: wordpress
      password: wordpresspass
      database: wordpress
      port: 3306
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: app.local
      annotations:
        kubernetes.io/ingress.class: nginx
