apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-stack
      version: 2.9.11
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  targetNamespace: monitoring
  values:
    loki:
      enabled: true
    promtail:
      enabled: true
    grafana:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - app-monitor.local
        annotations:
          kubernetes.io/ingress.class: nginx
